DEEPSEEK_API_KEY = "your-api-key"
DEEPSEEK_BASE_URL = "https://api.deepseek.com"
DEEPSEEK_MODEL = "deepseek-chat"

MIN_CONVERGENCE_MESSAGES = 80
MAX_AGENT_MESSAGE_CHARS = 520
DEFAULT_MAX_TURNS = 200
MIN_MAX_TURNS = 14
MAX_MAX_TURNS = 240

